on:
  pull_request:
     types:
       - closed
     branches:
       - master
jobs: 
  action-test-job:
    runs-on: ubuntu-latest
    name: Deploying the application
    steps:
      - name: Create a change event
        uses: PagerDuty/pagerduty-change-events-action@v1.0.0
        with:
          integration-key: '${{ secrets.PD_KLEY }}'
